{"uuid": "fdd021f5-50ae-4ec3-9dfb-9a0dd8783ee5", "children": ["423dda91-b06a-46c6-b5ce-0df8783c3b70", "33c7d442-edbd-498f-9fae-166e3ecb24fa", "1e973714-2c37-49a6-a0ae-d1d227652eda", "7f0a4215-aca6-4afe-aa4a-64b6593a9d27", "8e8bb466-bc03-4af9-9565-d542ce26281f", "a07f08fc-2507-442f-9d87-49f10f8288e8", "e6ae34b1-98d1-4297-927e-eb53a9ca0eaa", "fccf148a-20f7-49be-8046-1cec0fb1391f", "3d9a428b-af01-4d9d-ad35-adb093bd4c55", "c648ba3e-88d7-4222-bd91-914e71bf28b5", "2f748508-3a2b-41d3-be08-9ecdbd3a1baa", "4addebf5-c328-4a5e-9a8b-b5d6302d0b6c", "cfa95bff-10e6-4995-a9e0-9af1bd15356f", "a5244a50-b569-4248-9cd2-e2abb29995f5", "ad37682d-c19d-4b18-a913-19b8918439d0", "63e4302b-3bd8-4bab-aece-076375464fd9", "8e242b2c-c914-4e2b-91fd-fb573ebc671e", "ba57d1dd-dfce-481d-aeb0-af7de8ed5827", "aa4745b4-d569-4749-a6b3-82852a10492f", "3193f1b9-2d38-4994-8054-ad59a47a0c3c", "de3e5325-2ef1-4511-94a1-e680567e82a5", "6dc9fdde-56d1-424a-b288-995ce35402f0", "28c9c928-df3c-44f2-b923-298d3d636497", "3a4e7c97-f15f-4505-8578-8463696dfb7e", "a460a672-6a22-45d5-8467-eccc04727e68", "344816b8-d6ed-4dde-8bc5-d0480818d9e7", "45988fbf-562a-44c4-9459-2cbe40ef72e0", "2645cb85-7eff-443f-8da7-5bafa83d7fea"], "befores": [{"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142509814, "stop": 1646142513756}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142518929, "stop": 1646142522496}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142527513, "stop": 1646142531520}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142536586, "stop": 1646142540252}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142547371, "stop": 1646142552189}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142557416, "stop": 1646142561822}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited normally.\n  (chrome not reachable)\n  (The process started from chrome location C:\\Users\\Administrator\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\n\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 29, in access_web\n    driver = webdriver.Chrome()\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 76, in __init__\n    RemoteWebDriver.__init__(\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1646142569075, "stop": 1646142582397}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142594694, "stop": 1646142601822}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142606872, "stop": 1646142617872}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142625933, "stop": 1646142630116}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142635142, "stop": 1646142640399}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142645490, "stop": 1646142650176}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142657281, "stop": 1646142661999}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142667054, "stop": 1646142671852}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    bid = BidPage(access_web[0])\n"}, "start": 1646142679246, "stop": 1646142682740}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    yield (driver, lg, bid, user, index)  # 分割线，返回值\n"}, "start": 1646142687774, "stop": 1646142692551}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    yield (driver, lg)  # 分割线，返回值\n"}, "start": 1646142700676, "stop": 1646142704041}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    yield (driver, lg)  # 分割线，返回值\n"}, "start": 1646142709073, "stop": 1646142712433}, {"name": "access_web", "status": "broken", "statusDetails": {"message": "TypeError: 'function' object is not subscriptable\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Web_Framework_V2\\TestCases\\conftest.py\", line 33, in access_web\n    yield (driver, lg)  # 分割线，返回值\n"}, "start": 1646142719553, "stop": 1646142722895}], "start": 1646142719553, "stop": 1646142722929}